In [1]:
import pandas as pd
import os
import json
from pandas import json_normalize
from ast import literal_eval

In [2]:
pd.set_option('display.max_columns', None)

Download the CCV data from https://github.com/versotym/corpusCzechVerse and save them to your local folder.

In [7]:
# EDIT path to your data folder 
BASEDIR = '../../corpusCzechVerse/ccv/'

# Load the data

In [8]:
file_names = sorted(os.listdir(BASEDIR))

In [9]:
# number of books
len(file_names)

1305

In [13]:
%%time

no_poems = 0

for file_name in file_names:
    book = json_normalize(json.load(open(BASEDIR + file_name)))
    no_poems += len(book)
    
print('Number of poems:', no_poems)

Number of poems: 66428
CPU times: user 45.8 s, sys: 1.46 s, total: 47.3 s
Wall time: 48.4 s

In [14]:
%%time
books = []

for i in range(0, 600):
    book = json_normalize(json.load(open(BASEDIR + file_names[i])))
    books.append(book)

CPU times: user 35.9 ms, sys: 3.85 ms, total: 39.8 ms
Wall time: 38.2 ms

In [15]:
len(books)

1

In [16]:
df = pd.concat(books)

In [17]:
len(df)

43

In [18]:
df.head()

,book_id,poem_id,body,p_author.born,p_author.died,p_author.name,p_author.identity,biblio.motto_aut,biblio.b_subtitle,biblio.publisher,biblio.edition,biblio.motto,biblio.p_title,biblio.place,biblio.dedication,biblio.b_title,biblio.pages,biblio.year,biblio.signature,b_author.born,b_author.died,b_author.name,b_author.identity,results.poem
0,0001,0001-0000-0000-0001-0000,"[[{'text': 'Tvá loď jde po vysokém moři,', 'pu...",1841,1900,"Albert, Eduard","Albert, Eduard",None,Básně,"Šimáček, František; Unie",[1.],None,JAROSLAVU VRCHLICKÉMU,Praha,None,Na zemi a na nebi,[XVI]+104,1900,"Národní knihovna ČR, Praha; 54 H 2287",1841,1900,"Albert, Eduard","Albert, Eduard",None
1,0001,0001-0001-0000-0001-0000,"[[{'text': 'Už míza naplňuje stonky,', 'punct'...",1841,1900,"Albert, Eduard","Albert, Eduard",None,Básně,"Šimáček, František; Unie",[1.],None,ČASNĚ Z JARA,Praha,None,Na zemi a na nebi,[XVI]+104,1900,"Národní knihovna ČR, Praha; 54 H 2287",1841,1900,"Albert, Eduard","Albert, Eduard",None
2,0001,0001-0001-0000-0002-0000,"[[{'text': 'Už jaro výskalo si na potkání,', '...",1841,1900,"Albert, Eduard","Albert, Eduard",None,Básně,"Šimáček, František; Unie",[1.],None,ZMRZLÍCI,Praha,None,Na zemi a na nebi,[XVI]+104,1900,"Národní knihovna ČR, Praha; 54 H 2287",1841,1900,"Albert, Eduard","Albert, Eduard",None
3,0001,0001-0001-0000-0003-0000,"[[{'text': 'Teď slunce prošlo poledníkem,', 'p...",1841,1900,"Albert, Eduard","Albert, Eduard",None,Básně,"Šimáček, František; Unie",[1.],None,V POLEDNE,Praha,None,Na zemi a na nebi,[XVI]+104,1900,"Národní knihovna ČR, Praha; 54 H 2287",1841,1900,"Albert, Eduard","Albert, Eduard",None
4,0001,0001-0001-0000-0004-0000,"[[{'text': 'Skal nebetyčných shluky, řady,', '...",1841,1900,"Albert, Eduard","Albert, Eduard",None,Básně,"Šimáček, František; Unie",[1.],None,VEČERY V ALPÁCH,Praha,None,Na zemi a na nebi,[XVI]+104,1900,"Národní knihovna ČR, Praha; 54 H 2287",1841,1900,"Albert, Eduard","Albert, Eduard",None

In [20]:
poem_1 = df.body[0]

In [21]:
len(poem_1)

4

In [24]:
# poem_1
for stanza in poem_1:
    for line in stanza:
        print(line['text'])
    print('')  # end of stanza

Tvá loď jde po vysokém moři,
v ně brázdu jako stříbro reje,
svou přídu v modré vlny noří
a bok svůj pěnné do peřeje.

Tvá lana sviští, plachty duní
a třepe vlajka. V noční chvíli
zříš magický svit mořských tůní,
a ve snu, Albatros jak pílí.

Já samotním, jsem na ostrově,
ohýnek topím, rybku lově
zasedám na břeh za večera.

Dým v kotoučích se modrých krade,
kdes písklo ptáče, ještě mladé,
tma na mne hrozí z pološera.

In [16]:
# save the loaded books into a single file
df.to_csv('0001-0677.csv', index=False)

# Read complete df with all books

In [26]:
import pandas as pd

df = pd.read_csv('../data/books.csv', low_memory=False)

In [27]:
df.head()

,book_id,poem_id,body,p_author.born,p_author.died,p_author.name,p_author.identity,biblio.motto_aut,biblio.b_subtitle,biblio.publisher,biblio.edition,biblio.motto,biblio.p_title,biblio.place,biblio.dedication,biblio.b_title,biblio.pages,biblio.year,biblio.signature,b_author.born,b_author.died,b_author.name,b_author.identity,results.poem
0,1,0001-0000-0000-0001-0000,"[[{'text': 'Tvá loď jde po vysokém moři,', 'pu...",1841.0,1900.0,"Albert, Eduard","Albert, Eduard",NaN,Básně,"Šimáček, František; Unie",[1.],NaN,JAROSLAVU VRCHLICKÉMU,Praha,NaN,Na zemi a na nebi,[XVI]+104,1900,"Národní knihovna ČR, Praha; 54 H 2287",1841.0,1900.0,"Albert, Eduard","Albert, Eduard",NaN
1,1,0001-0001-0000-0001-0000,"[[{'text': 'Už míza naplňuje stonky,', 'punct'...",1841.0,1900.0,"Albert, Eduard","Albert, Eduard",NaN,Básně,"Šimáček, František; Unie",[1.],NaN,ČASNĚ Z JARA,Praha,NaN,Na zemi a na nebi,[XVI]+104,1900,"Národní knihovna ČR, Praha; 54 H 2287",1841.0,1900.0,"Albert, Eduard","Albert, Eduard",NaN
2,1,0001-0001-0000-0002-0000,"[[{'text': 'Už jaro výskalo si na potkání,', '...",1841.0,1900.0,"Albert, Eduard","Albert, Eduard",NaN,Básně,"Šimáček, František; Unie",[1.],NaN,ZMRZLÍCI,Praha,NaN,Na zemi a na nebi,[XVI]+104,1900,"Národní knihovna ČR, Praha; 54 H 2287",1841.0,1900.0,"Albert, Eduard","Albert, Eduard",NaN
3,1,0001-0001-0000-0003-0000,"[[{'text': 'Teď slunce prošlo poledníkem,', 'p...",1841.0,1900.0,"Albert, Eduard","Albert, Eduard",NaN,Básně,"Šimáček, František; Unie",[1.],NaN,V POLEDNE,Praha,NaN,Na zemi a na nebi,[XVI]+104,1900,"Národní knihovna ČR, Praha; 54 H 2287",1841.0,1900.0,"Albert, Eduard","Albert, Eduard",NaN
4,1,0001-0001-0000-0004-0000,"[[{'text': 'Skal nebetyčných shluky, řady,', '...",1841.0,1900.0,"Albert, Eduard","Albert, Eduard",NaN,Básně,"Šimáček, František; Unie",[1.],NaN,VEČERY V ALPÁCH,Praha,NaN,Na zemi a na nebi,[XVI]+104,1900,"Národní knihovna ČR, Praha; 54 H 2287",1841.0,1900.0,"Albert, Eduard","Albert, Eduard",NaN

In [28]:
len(df)

66428

In [29]:
df.dtypes

book_id                int64
poem_id               object
body                  object
p_author.born        float64
p_author.died        float64
p_author.name         object
p_author.identity     object
biblio.motto_aut      object
biblio.b_subtitle     object
biblio.publisher      object
biblio.edition        object
biblio.motto          object
biblio.p_title        object
biblio.place          object
biblio.dedication    float64
biblio.b_title        object
biblio.pages          object
biblio.year           object
biblio.signature      object
b_author.born        float64
b_author.died        float64
b_author.name         object
b_author.identity     object
results.poem         float64
dtype: object

# Store x% sample for testing

In [6]:
x = 0.2

In [7]:
books = df.sample(frac=x, random_state=42, ignore_index=True)

In [8]:
books

,book_id,poem_id,body,p_author.born,p_author.died,p_author.name,p_author.identity,biblio.motto_aut,biblio.b_subtitle,biblio.publisher,...,biblio.dedication,biblio.b_title,biblio.pages,biblio.year,biblio.signature,b_author.born,b_author.died,b_author.name,b_author.identity,results.poem
0,623,0001-0004-0000-0008-0000,"[[{'text': 'Je-li v domě hezká dcera, ', 'punc...",1842.0,1924.0,"Martinec, Jaroslav","Martinec, Jaroslav",NaN,NaN,"Grégr, Eduard; Dattel, Ferdinand",...,NaN,Básně,102,1872,ÚČL AV ČR; 849 VIII 1,1842.0,1924.0,"Martinec, Jaroslav","Martinec, Jaroslav",NaN
1,638,0001-0001-0000-0167-0000,"[[{'text': 'Z obchodu nekalého, špinavého vytě...",1857.0,1909.0,"Menhard Litoměřický, Xaver","Menhard, František Ladislav",NaN,Nevázané řeči ve vázané řeči,"Knapp, Mamert",...,NaN,Divoké ovoce,176,1892,"Národní knihovna ČR, Praha; 54 K 622",1857.0,1909.0,"Menhard Litoměřický, Xaver","Menhard, František Ladislav",NaN
2,281,0001-0000-0000-0004-0004,"[[{'text': 'Hle! na jezeru hvězdném', 'punct':...",1813.0,1881.0,"Jablonský, Boleslav","Jablonský, Boleslav",NaN,NaN,"Spurný, Jan",...,NaN,Básně,190,1841,ÚČL AV ČR; Staré tisky 111,1813.0,1881.0,"Jablonský, Boleslav","Jablonský, Boleslav",NaN
3,1283,0001-0000-0000-0013-0000,[[{'text': 'Král Louis vyjel na lov s družinou...,1883.0,1919.0,"Hašek, Roman","Hašek, Roman",NaN,1902-1903,"Popelka, Václav",...,NaN,Pohádka zelených očí a verše o stesku i výsměchu,96,1904,ÚČL AV ČR; P 515,1883.0,1919.0,"Hašek, Roman","Hašek, Roman",NaN
4,395,0001-0004-0000-0009-0000,[[{'text': 'Blíž cesty za městem vůz loutkářův...,1866.0,1938.0,"Klášterský, Antonín","Klášterský, Antonín",NaN,Básně,"Šimáček, František; Kabinetní knihovna",...,NaN,Srdce i duše,188,1894,ÚČL AV ČR; P 341,1866.0,1938.0,"Klášterský, Antonín","Klášterský, Antonín",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19923,591,0001-0002-0000-0036-0000,"[[{'text': 'Nákrční šátek otočen je těsně', 'p...",1864.0,1942.0,"Machar, Josef Svatopluk","Machar, Josef Svatopluk",NaN,Psáno 1911-1916,"Šolc, Karel; Šimáček, František",...,NaN,"Oni (in Roky za století 1, in Básnické dílo J....",216,1921,"Národní knihovna ČR, Praha; 54 J 5714/VI",1864.0,1942.0,"Machar, Josef Svatopluk","Machar, Josef Svatopluk",NaN
19924,899,0001-0003-0000-0002-0000,"[[{'text': 'Bál jsem se, léta co plynou,', 'pu...",1864.0,1928.0,"Sova, Antonín","Sova, Antonín",NaN,Z r. 1921-1922,"Štorch-Marien, Otakar; Aventinum; Obzina, Fran...",...,NaN,Básně nesobeckého srdce (in Dílo Antonína Sovy...,111,1922,ÚČL AV ČR; 167 VIII 23,1864.0,1928.0,"Sova, Antonín","Sova, Antonín",NaN
19925,895,0001-0000-0000-0008-0000,"[[{'text': 'Hajej, nynej, má Panenko,', 'punct...",1845.0,1912.0,"Sládek, Josef Václav","Sládek, Josef Václav",NaN,Čtyřiadvacet písní pro děti,"Otto, Jan",...,NaN,Zlatý máj,66,1887,"Národní knihovna ČR, Praha; 54 D 1220",1845.0,1912.0,"Sládek, Josef Václav","Sládek, Josef Václav",NaN
19926,23,0001-0000-0000-0007-0000,"[[{'text': 'Soucite, ty chvějný, bájný květe,'...",1874.0,1948.0,"Bitnar, Vilém","Bitnar, Vilém",NaN,NaN,"Básnické obzory katolické; Bitnar, Vilém; Stiv...",...,NaN,Biblické rapsodie,56,1896,ÚČL AV ČR; 1400 VIII 1,1874.0,1948.0,"Bitnar, Vilém","Bitnar, Vilém",NaN
19927,754,0001-0000-0000-0074-0000,"[[{'text': 'Nejsem u Vás a jsem přece ', 'punc...",1849.0,1919.0,"Nečas, Jan Evangelista","Nečas, Jan Evangelista",NaN,NaN,"Nečas, Jan Evangelista; Novotný, [?]; Misák, [?]",...,NaN,Sto písní k dobré duši,30,1911,ÚČL AV ČR; P 663,1849.0,1919.0,"Nečas, Jan Evangelista","Nečas, Jan Evangelista",NaN

In [9]:
books.to_csv('../data/books_frac_0.2.csv', index=False)

# Store just poem id and text (for embeddings)

In [24]:
len(df)

66428

In [25]:
df['book_poem_id'] = df['book_id'].astype(str) + '_' + df['poem_id']

In [26]:
df = df[['book_poem_id', 'body']]

In [27]:
df.head()

,book_poem_id,body
0,1_0001-0000-0000-0001-0000,"[[{'text': 'Tvá loď jde po vysokém moři,', 'pu..."
1,1_0001-0001-0000-0001-0000,"[[{'text': 'Už míza naplňuje stonky,', 'punct'..."
2,1_0001-0001-0000-0002-0000,"[[{'text': 'Už jaro výskalo si na potkání,', '..."
3,1_0001-0001-0000-0003-0000,"[[{'text': 'Teď slunce prošlo poledníkem,', 'p..."
4,1_0001-0001-0000-0004-0000,"[[{'text': 'Skal nebetyčných shluky, řady,', '..."

In [29]:
%%time

texts = []

for index, p in df.iterrows():
    text = ''
    poem = literal_eval(p['body'])
    for stanza in poem:
        for line in stanza:
            text += line['text']
            text += ' '
    
    if index % 10000 == 0:
        print(index)    
    
    texts.append(text)

0
10000
20000
30000
40000
50000
60000
CPU times: user 12min 21s, sys: 19.7 s, total: 12min 40s
Wall time: 12min 40s

In [30]:
len(texts)

66428

In [31]:
df['text'] = texts

In [32]:
texts_df = df.drop(columns=['body'])

In [33]:
texts_df

,book_poem_id,text
0,1_0001-0000-0000-0001-0000,"Tvá loď jde po vysokém moři, v ně brázdu jako ..."
1,1_0001-0001-0000-0001-0000,"Už míza naplňuje stonky, už přišly modré anemo..."
2,1_0001-0001-0000-0002-0000,"Už jaro výskalo si na potkání, kosové pěli ze ..."
3,1_0001-0001-0000-0003-0000,"Teď slunce prošlo poledníkem, dal znamení, a t..."
4,1_0001-0001-0000-0004-0000,"Skal nebetyčných shluky, řady, jež vystupují z..."
...,...,...
66423,1689_0001-0000-0000-0026-0000,"U altánu bílý jasmín opojivou vůni dýše, zkolé..."
66424,1689_0001-0000-0000-0027-0000,"Nad tůní honí se černých mraků let, do vody kl..."
66425,1689_0001-0000-0000-0028-0000,Podle cesty hlohu keře sladkohořkou vůní chvát...
66426,1689_0001-0000-0000-0029-0000,Na lesní stráni zalité sluncem rosou se třpytí...
66427,1689_0001-0000-0000-0030-0000,"Lučinou potůček ubíhá v spěch, zlatem mu blato..."

In [34]:
texts_df['text'][13]

'Byl z Bernardýnů, ne však čisté krve a přišel na svět v parku široširém a skončil tamtéž. Nemotorný prve, vyrostl statně; pak plul žití vírem. Byl strážce věrný. Mezi námi žije vyčichal, rodinná co monarchie. Přede mnou sedal, jako sfinga v poušti, jak stráž, jež pána nikdy neopouští. Když na trh směl si vyjít s mojí paní – jak v punčochách by komorník šel za ní. Na světě nejmilejší jemu děti, jej tahaly a válely jím v smetí; jim velbloudem byl, mostem, hasičem, jak chtěly. Nezaúpěl pod bičem. My odpustili, když jak divý běhal, i to, že rád si do resedek lehal. Byl náš. Pak hostec vjel mu do všech oudů. Tu v zimě do domu jsme dali boudu. Už smrt mu chraptívala do štěku. A konec konců – skonal jednou v podzimí a zahrabán do zeleného mlází. – Byl v mnohých věcech vzorem – člověku. Co z nás by teprv mohlo být? Nám schází rozhodně styk s bytostmi vyššími. '

In [35]:
texts_df.to_csv('../data/texts.csv', index=False)

# Store body with book_poem_id

In [12]:
df['book_poem_id'] = df['book_id'].astype(str) + '_' + df['poem_id']

In [13]:
df = df[['book_poem_id', 'body']]

In [18]:
df.to_csv('../data/bodies.csv', index=False)

# Store book_poem_id, lemmas and their POS tags

In [6]:
df['book_poem_id'] = df['book_id'].astype(str) + '_' + df['poem_id']

In [7]:
df = df[['book_poem_id', 'body']]

In [9]:
lemmas_col = []

# extract lemmas and pos tags
for index, poem in df.iterrows():
    if index % 100 == 0:
        print(index, end=' ')
        
    lemmas_poem = []
    body = literal_eval(poem['body'])
    for stanza in body:
        for line in stanza:
            for word in line['words']:
                # if POS tag is Noun, Adjective or Verb
                pos = word['morph'][0]
                lemmas_poem.append((word['lemma'], pos))
    lemmas_col.append(lemmas_poem)

0 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 7100 7200 7300 7400 7500 7600 7700 7800 7900 8000 8100 8200 8300 8400 8500 8600 8700 8800 8900 9000 9100 9200 9300 9400 9500 9600 9700 9800 9900 10000 10100 10200 10300 10400 10500 10600 10700 10800 10900 11000 11100 11200 11300 11400 11500 11600 11700 11800 11900 12000 12100 12200 12300 12400 12500 12600 12700 12800 12900 13000 13100 13200 13300 13400 13500 13600 13700 13800 13900 14000 14100 14200 14300 14400 14500 14600 14700 14800 14900 15000 15100 15200 15300 15400 15500 15600 15700 15800 15900 16000 16100 16200 16300 16400 16500 16600 16700 16800 16900 17000 17100 17200 17300 17400 17500 17600 17700 17800 17900 18000 18100 18200 18300 18400 18500 18600 18700 18800 18900 19000 19100 19200 19300 19400 19500 19600 19700 19800 19900 20000 20100 20200 20300 20400 20500 20600 20700 20800 20900 21000 21100 21200 21300 21400 21500 21600 21700 21800 21900 22000 22100 22200 22300 22400 22500 22600 22700 22800 22900 23000 23100 23200 23300 23400 23500 23600 23700 23800 23900 24000 24100 24200 24300 24400 24500 24600 24700 24800 24900 25000 25100 25200 25300 25400 25500 25600 25700 25800 25900 26000 26100 26200 26300 26400 26500 26600 26700 26800 26900 27000 27100 27200 27300 27400 27500 27600 27700 27800 27900 28000 28100 28200 28300 28400 28500 28600 28700 28800 28900 29000 29100 29200 29300 29400 29500 29600 29700 29800 29900 30000 30100 30200 30300 30400 30500 30600 30700 30800 30900 31000 31100 31200 31300 31400 31500 31600 31700 31800 31900 32000 32100 32200 32300 32400 32500 32600 32700 32800 32900 33000 33100 33200 33300 33400 33500 33600 33700 33800 33900 34000 34100 34200 34300 34400 34500 34600 34700 34800 34900 35000 35100 35200 35300 35400 35500 35600 35700 35800 35900 36000 36100 36200 36300 36400 36500 36600 36700 36800 36900 37000 37100 37200 37300 37400 37500 37600 37700 37800 37900 38000 38100 38200 38300 38400 38500 38600 38700 38800 38900 39000 39100 39200 39300 39400 39500 39600 39700 39800 39900 40000 40100 40200 40300 40400 40500 40600 40700 40800 40900 41000 41100 41200 41300 41400 41500 41600 41700 41800 41900 42000 42100 42200 42300 42400 42500 42600 42700 42800 42900 43000 43100 43200 43300 43400 43500 43600 43700 43800 43900 44000 44100 44200 44300 44400 44500 44600 44700 44800 44900 45000 45100 45200 45300 45400 45500 45600 45700 45800 45900 46000 46100 46200 46300 46400 46500 46600 46700 46800 46900 47000 47100 47200 47300 47400 47500 47600 47700 47800 47900 48000 48100 48200 48300 48400 48500 48600 48700 48800 48900 49000 49100 49200 49300 49400 49500 49600 49700 49800 49900 50000 50100 50200 50300 50400 50500 50600 50700 50800 50900 51000 51100 51200 51300 51400 51500 51600 51700 51800 51900 52000 52100 52200 52300 52400 52500 52600 52700 52800 52900 53000 53100 53200 53300 53400 53500 53600 53700 53800 53900 54000 54100 54200 54300 54400 54500 54600 54700 54800 54900 55000 55100 55200 55300 55400 55500 55600 55700 55800 55900 56000 56100 56200 56300 56400 56500 56600 56700 56800 56900 57000 57100 57200 57300 57400 57500 57600 57700 57800 57900 58000 58100 58200 58300 58400 58500 58600 58700 58800 58900 59000 59100 59200 59300 59400 59500 59600 59700 59800 59900 60000 60100 60200 60300 60400 60500 60600 60700 60800 60900 61000 61100 61200 61300 61400 61500 61600 61700 61800 61900 62000 62100 62200 62300 62400 62500 62600 62700 62800 62900 63000 63100 63200 63300 63400 63500 63600 63700 63800 63900 64000 64100 64200 64300 64400 64500 64600 64700 64800 64900 65000 65100 65200 65300 65400 65500 65600 65700 65800 65900 66000 66100 66200 66300 66400

In [10]:
df['lemmas'] = lemmas_col

In [12]:
df = df[['book_poem_id', 'lemmas']]

In [13]:
df.head(3)

,book_poem_id,lemmas
0,1_0001-0000-0000-0001-0000,"[(tvůj, P), (loď, N), (jít, V), (po, R), (vyso..."
1,1_0001-0001-0000-0001-0000,"[(už, D), (míza, N), (naplňovat, V), (stonek, ..."
2,1_0001-0001-0000-0002-0000,"[(už, D), (jaro, N), (výskat, V), (se, P), (na..."

In [15]:
df.shape

(66428, 2)

In [14]:
df.to_csv('../data/lemmas.csv', index=False)